//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Checkpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Categories = new HashSet<Category>();
            this.Categories1 = new HashSet<Category>();
        }
    
        public int Pid { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> PostId_PostId { get; set; }
        public Nullable<int> Price_PostId { get; set; }
        public Nullable<int> ProductId_PostId { get; set; }
        public Nullable<int> Post_PostId { get; set; }
        public Nullable<int> Post1_PostId { get; set; }
        public Nullable<int> Post2_PostId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        public virtual Post Post { get; set; }
        public virtual Post Post1 { get; set; }
        public virtual Post Post2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories1 { get; set; }
        public virtual Post Post3 { get; set; }
        public virtual Post Post11 { get; set; }
        public virtual Post Post21 { get; set; }
    }
}
