//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Checkpoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.Users = new HashSet<User>();
            this.Users1 = new HashSet<User>();
            this.Users11 = new HashSet<User>();
        }
    
        public int ReviewId { get; set; }
        public string ReviewText { get; set; }
        public int Rating { get; set; }
        public Nullable<int> AdminId_AdminId { get; set; }
        public Nullable<int> ReviewedUserId_UserId { get; set; }
        public Nullable<int> ReviewerId_UserId { get; set; }
        public Nullable<int> Admin_AdminId { get; set; }
        public Nullable<int> User_UserId { get; set; }
        public Nullable<int> User_UserId1 { get; set; }
        public Nullable<int> User_UserId2 { get; set; }
        public Nullable<int> User1_UserId { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        public virtual Admin Admin1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User11 { get; set; }
        public virtual User User21 { get; set; }
        public virtual User User3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users11 { get; set; }
    }
}
